name: jikan_api
description: Dart wrapper for the Jikan API, an unofficial MyAnimeList API.
version: 1.0.0+1
author: Javier Rosales <javi.malaga12@gmail.com>
homepage: https://github.com/javoeria/jikan-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  built_value: ^6.8.2
  built_collection: ^4.2.2

dev_dependencies:
  build_runner: ^1.7.1
  built_value_generator: ^6.8.2
  test: ^1.9.3
