name: jikan_dart
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: rafal.wachol <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0
  built_value: ^6.1.6
  built_collection: ^4.0.0
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  built_value_generator: ^6.1.6
  test: ^1.0.0
