name: jikan_dart
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: rafal.wachol <email@example.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  built_value: ^6.7.1
  built_collection: ^4.2.2

dev_dependencies:
  build_runner: ^1.7.1
  built_value_generator: ^6.7.1
  test: ^1.9.2
