name: jikan_api
version: 1.1.0
description: Dart wrapper for the Jikan API, an unofficial MyAnimeList API.
homepage: https://github.com/javoeria/jikan-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  built_value: ^7.0.0
  built_collection: ^4.3.0

dev_dependencies:
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0
  test: ^1.9.4
