name: jikan_api
version: 1.2.0
description: Dart wrapper for the Jikan API, an unofficial MyAnimeList API.
homepage: https://github.com/javoeria/jikan-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  built_value: ^7.0.9
  built_collection: ^4.3.2

dev_dependencies:
  build_runner: ^1.8.0
  built_value_generator: ^7.0.9
  test: ^1.14.2
